---
title: "git_00"
author: "Joseph cobian"
date: "2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
A BOAT beneath a sunny sky,
Lingering onward dreamily
In an evening of July --
Children three that nestle near,
Eager eye and willing ear,

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Two roads diverged in a yellow wood,
And sorry I could not travel both
And be one traveler, long I stood
And looked down one as far as I could
To where it bent in the undergrowth

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea,
Shining with all his might

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
They jumped from the burning floors—
one, two, a few more,
higher, lower.

The photograph halted them in life,
and now keeps them   
above the earth toward the earth.

Each is still complete,
with a particular face
and blood well hidden.

There’s enough time
for hair to come loose,
for keys and coins
to fall from pockets.

They’re still within the air’s reach,
within the compass of places
that have just now opened.

I can do only two things for them—
describe this flight
and not add a last line